### ISSUE TITLE
Include year/(author?) in title

### ISSUE THREAD

**Issue by corajr** [corajr/zotero-voyant-export#5]
In order to take advantage of chronological aspects of Voyant, the titles should begin with the year (if available). Potentially it should also include the author, as that info doesn't seem to be surfaced in Voyant.

**Comment by sgsinclair** [comment]
I've been contacted independently by folks interested in ordering documents by any available date information, @corajr is this a plugin you're still interested in working on or should I check at my end about some possible help?
