### ISSUE TITLE
Installed on windows, no "export to voyant..."

### ISSUE THREAD

**Issue by wasmetqall** [corajr/zotero-voyant-export#8]
zotero 5.0.4 & win10,and I've already tried reinstalled it but still not working.

**Comment by eparimbelli** [comment]
I was able to use the plugin some months ago, now I also don't see the "export to voyant" menu.
zotero 5.0.29 and linux ubuntu 16.04LTS

**Comment by healthlawgeek** [comment]
I had used the plugin successfully with zotero 5.0.x & Win 10 successfully less than a month ago, but now I have the same issue with no "export to voyant" option. I tried reviewing the UI.js file, but am in way beyond my knowledge base for how the add-on accesses zotero's export menu. Also, I tried to reinstall zotero, then the add-on to no avail. If I knew what I was doing I could help, but there is little documentation here to go from...

**Comment by DancingQuanta** [comment]
Same issue here!

**Comment by gabefair** [comment]
Thank you for creating this extension. I'm here to report that I'm also having issues using it with windows 10 and Firefox 60. If you provide a flattr or patron page, I would donate to it. Thanks

**Comment by BenjaminHCCarr** [comment]
Hi All, you may not be aware, but `Zotero 5.x` is completely different from everything before it, and a stepping stone to a second complete rewrite.

This and most other plugins require massive rewrites to work with `v5`, that said, if someone wants to setup Patreon/flattr and fork it, that IS the beauty of *open source*.

**Comment by schignel** [comment]
I'm having the same issue on Zotero 5.0.47, Windows 7.

**Comment by sdspieg** [comment]
No progress made on this? I have the same problem on Windows...
