### ISSUE TITLE
Plugin not working and disappears after restarting zotero 

### ISSUE THREAD

**Issue by avila** [corajr/zotero-voyant-export#9]
## Specs: 
zotero standalone version: 5.0.52
Zotero Voyant Export version: 0.0.4

## issue
After installing, a new item is added to the `right-click` menu, when selecting collections. But when trying to export a collection to voyant nothing happens. That is, I cannot select a folder to export the zip-file. 

I tried restarting zotero but then the menu entry is gone, although the add-on is is still visible under `tools > add-ons`.

**Comment by sdspieg** [comment]
For me removing and then re-installing it made the item appear again.  I could also select a filename, but the resulting zip-file was only 1kb big and contained only an empty bagit.txt file.

**Comment by tohigu** [comment]
Exact same behavior over here. Seems like some files are being created in the tmp folder but nothing else happens.

Here is the debug log:
[https://pastebin.com/3vxTqJZd](url)
